# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.3

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: gem install bundler -v 2.0.2

      - run:
          name: install dependencies
          command: |
            bundle install

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec

      # run rubocop!
      - run:
          name: run rubocop
          command: |
            bundle exec rubocop
